public  class Company {
/*

    public String companyName;
    public String ceo;
    public Integer employeeCount;
    public Long revenue;

      private List<Client> customers = new list<Client>(); // class also a datatype
            public void addCustomer(String ClientName,String website,String email,long phone){
             Client customer = new Client(ClientName,website,email,phone);
                customers.add(customer);
               // System.debug('Customer Name: '+customer.clientName+', Website: '+customer.website+', Phone: '+customer.phone+', Email: '+customer.email);
            
            }

        public void getAllCustomers(){
            for(client customerVar : customers){
                    system.System.debug('customerName is'+customerVar);
            }
        }

    public class Client{

        public String ClientName;
        public String website;
        public String email;
        public long phone;

        client(String ClientName,String website,String email,long phone){
            this.ClientName = clientName;
            this.website= website;
            this.email= email;
            this.phone = phone;
        }
    }
    List<account> acclist = [select id,name,account.]
}

// /String queryString = 'Select id,Name from account';

// queryString + = 'WHERE isactive = '\true\' and accountnumber = '\ 178687\' '

//System.debug('QueryString'+queryString);
*/
}